CREATE TABLE Alerts (
    AlertID INT AUTO_INCREMENT PRIMARY KEY,
    RoomID INT,
    AlertTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    Message TEXT,
    Resolved BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (RoomID) REFERENCES Rooms(RoomID)
);